/*
set @=%~f0&call "%~dp0cube-p" %*

@del /a /f /q "%wd%\TPPL.PRJ" &::! to prevent resetting the counter

VOYAGER "%~dpnx0" %args%

@%SystemRoot%\System32\timeout 10 &goto:eof&::█████████████████*/ %add2script%

RUN PGM=NETWORK
  NETI = "%dpnx1%"
  NETO = "%dpn1%-cleaned.net",
  INCLUDE=OBJECTID,SHAPE_LENG,DISTANCE,JUR,SCREEN,FTYPE,TOLL,TOLLGRP,AMLANE,AMLIMIT,PMLANE,PMLIMIT,OPLANE,OPLIMIT,EDGEID,LINKID,NETYEAR,PROJECTID[8],TRANTIME,WKTIME,MODE,SPEED,ATYPEOVER,TAZ,ATYPE,OPENINGYEAR,GANTRYID,MINTOLL,TOLLDISTANCE,ORDER,GP_A,GP_B,PLAZAID,ODID,TMC1[11],TMC2[9],TMC3[9],TMC4[9],TMC5[1],XMID,YMID,DIRLETTER[1],DIRNUM,DEG,ACCESS,ACCESSPOINT,ROADSEGMENT,CORRIDOR,ROADTYPE,SEGMENT,DIRECTION,SPDCLASS,CAPCLASS,I4AMSPD,I4M1SPD,I4M2SPD,I4PMSPD,DEFLATIONFTR,AMTOLL,PMTOLL,OPTOLL,AMTOLL_VP,PMTOLL_VP,OPTOLL_VP,AMHTIME,PMHTIME,OPHTIME,TIMEPEN,TOLL_DELTA_AM,TOLL_DELTA_PM,LW_TIMEPEN_1,COMP,I4AMFLOW,I4AMTIMEP,I4AMTIMEPEN,I4AMSOV,I4AMHV2,I4AMHV3,I4AMCV,I4AMTRK,I4AMAPX,I4AMSOVTOLL,I4AMHV2TOLL,I4AMHV3TOLL,I4AMCVTOLL,I4AMTRKTOLL,I4AMAPXTOLL,I4AMAUTO,I4AMAUTOT,I4AMAUTOF,I4AMREV,I4AMVOL,I4AMVMT,I4AMFFSPD,AMHRLKCAP,AMHRLNCAP,I4AMVC,I4AMVDF,I4AMTIMEMODEL,I4AMTIME
ENDRUN
